### ISSUE TITLE
Support AWS CDK v2 

### ISSUE THREAD

**Issue by jumic** [cdklabs/cdk-triggers#287]
It would be great to release a cdk-triggers version that supports CDK v2 so that it could be used in v2 CDK projects.

I would like to use it for writing [test assertions](https://github.com/projen/projen/blob/main/docs/awscdk.md#writing-test-assertions) in projen CDK v2 projects.

Is there already a strategy to migrate libs like this one to CDK v2? Is it necessary to publish a v1 and a v2 version in parallel during a transition period? Or is it possible to migrate this repository to v2 and stop publishing the v1 version?

**Comment by Chriscbr** [comment]
I think the most likely path forward would be to upgrade the library directly to support v2, since this is an experimental library, and since that's what we did with `cdk-watchful` and so far nobody has complained. :)

**Comment by Chriscbr** [comment]
cdk-triggers has been bumped to v0.1.x to support CDK v2! 🎉

**Comment by jumic** [comment]
@Chriscbr Thank you very much. I updated my example project to the new version and it works fine.
