### ISSUE TITLE
Compatibility with monocdk

### ISSUE THREAD

**Issue by avi-jain** [cdklabs/cdk-triggers#317]
Is there a version of this that uses monocdk instead of aws-cdk/core? (are there plans to release one, if not?)

Thanks!

**Comment by Chriscbr** [comment]
Hi @avi-jain , I don't believe we have any plans to create a version of this using monocdk at the moment. We recommend customers to upgrade to AWS CDK v2 following their organization's guidance.

You're welcome to re-create the basic trigger construct within your own projects though if you're locked out of AWS CDK v2 for some reason -- the source code is relatively short / shouldn't be too hard to translate to the CDK language you are using: https://github.com/cdklabs/cdk-triggers/blob/main/src/triggers.ts
